### ISSUE TITLE
当token为空时，系统不退到登录界面，显示的统计图表页面

### ISSUE THREAD

**Issue by habitshine** [MaiYuan/Admin5#5]
当token为空时，系统不退到登录界面，显示的统计图表页面

**Comment by 383514580** [comment]
我有判断为空啊, 你说的空是" "带空格吗?

**Comment by 383514580** [comment]
![image](https://cloud.githubusercontent.com/assets/8264787/24484925/787a3e7a-1533-11e7-9ed3-c5d0043464ad.png)
